### PR TITLE
Add icon for shared pedestrian and cyclist crossing

### PR DESCRIPTION
**Pull request by hikemaniac**
This is a properly rebased version of #54. Sorry for messing that PR up. 😅
This PR adds an icon for a crossing for both cyclists and pedestrians. I used the already existing `pedestrian_crosswalk` and the `pedestrian_and_cyclist` icons as the basis for the new icon.

### CODE REVIEW

**Comment by quincylvania** [comment]
@hikemaniac Thanks, looks good! In the future it'd be helpful if you could add a screenshot preview of the icon but it's no big deal.

**Comment by bhousel** [comment]
Not a huge deal, but I'd like to clean it up later to use a 15px by 15px viewbox.

**Comment by quincylvania** [comment]
> I'd like to clean it up later to use a 15px by 15px viewbox.

Good idea. I took care of this and also shortened the name to make it more manageable.

**Comment by bhousel** [comment]
> Good idea. I took care of this and also shortened the name to make it more manageable.

Thanks! 👍

**Comment by hikemaniac** [comment]
Thank you a lot! :+1: Interestingly, Inkscape displayed my icon with a 15x15px viewbox. I have no idea what went wrong. :confused:

**Comment by quincylvania** [comment]
The size was 15x15 but the coordinates were defined in a smaller range and then translated to appear centered in the 15x15 box. It's a bit confusing.

**Comment by hikemaniac** [comment]
@quincylvania Thank you for explaining! Inkscape really does seem to be a very creative piece of software. 😆

**Pull request merged**
