### PR TITLE
add an icon for pedestrian crossing signals (traffic light controlled…

### PR DESCRIPTION
**Pull request by dieterdreist**
… pedestrian crossings)

references: https://github.com/bryceco/GoMap/issues/525

### CODE REVIEW

**Comment by dieterdreist** [comment]
is there an issue with the icon? I thought this would be uncontested.

**Comment by bhousel** [comment]
Sorry I wasn't paying much attention to this repo lately.
It looks like you just copied the railway signals icon - is this a mistake?
Screen Shot 2021-07-06 at 9 26 51 AM

**Comment by dieterdreist** [comment]
oops, the railway signals is the same? I actually took the highway traffic signals icon and removed the third circle. This is following the same concept as they do it in JOSM. 

Sorry, I wasn't aware it is already used for railway signals. If the icon is not needed, maybe we can simply show this icon also for pedestrian crossings that are controlled by traffic signals? These are very common and much more of interest to a "generic" person than railway signals (expert niche). I would guess that there wouldn't be overlap between railway signals (which are on rails) and pedestrian crossings (which are on roads)?

**Comment by bhousel** [comment]
This is a repo where we collect icons, and I can't accept a PR for an icon that we already have..

Downstream projects can use the temaki icons for whatever purpose they want - If someone wants to use our railway signals icon to represent a signalized pedestrian crossing, that's ok with me..

I kind of think it would make more sense for these projects to use one of these existing crossing-like icons that temaki provides:
* pedestrian.svg 
* pedestrian_crosswalk.svg

**Comment by dieterdreist** [comment]
Am Di., 6. Juli 2021 um 17:39 Uhr schrieb Bryan Housel <
***@***.***>:

> This is a repo where we collect icons, and I can't accept a PR for an icon
> that we already have..
>
> Downstream projects can use the temaki icons for whatever purpose they
> want - If someone wants to use our railway signals icon to represent a
> signalized pedestrian crossing, that's ok with me..
>
> I kind of think it would make more sense for these projects to use one of
> these existing crossing-like icons that temaki provides:
>
>    - pedestrian.svg
>    <https://camo.githubusercontent.com/5d7d79316f6f34849bf55cab876f3d13ed315034b74667adaf9702c6edc9db0a/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6964656469746f722f74656d616b69406d61696e2f69636f6e732f7065646573747269616e2e737667>
>    - pedestrian_crosswalk.svg
>    <https://camo.githubusercontent.com/f7631ba8a5b781e8022a6a19aa5034fa36033b63d60e043f1aad37ba4e7f1463/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f6964656469746f722f74656d616b69406d61696e2f69636f6e732f7065646573747269616e5f63726f737377616c6b2e737667>
>
>
the scope of the icon is to highlight the traffic lights, the icons you
show are already used for marked crossings

**Pull request closed without merging**
